name: Main Workflow

on:
    workflow_dispatch:
    push:

jobs:
    sample:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3.5.3

        # - name: Run Hello World
        #   run: echo Hello, world!
        
        - name: Run Python script
          run: |
            chmod +x wrapper_script.sh 
            ./wrapper_script.sh python main.py
        
    # caller-workflow-passing-data:
    #   uses: AksharaDeena/test/.github/workflows/sub.yml@main
    #   secrets: inherit
      # with:
      #   config-value: ${{ inputs.config-value }}
      # secrets:
      #   envPAT: ${{ secrets.envPAT }}
