name: Sub Workflow

on:
    workflow_dispatch:
    workflow_call:
      inputs:
        config-path:
          required: false
          type: string
          default: ./github/test.yml
        config-value:
          required: false
          type: string
          default: testvalue
      secrets:
        envPAT:
          required: false

jobs:
    sub-job1:
      runs-on: ubuntu-20.04
      steps:
      - name: sub-job1
        run: echo sub-job1 in Sub Workflow

    reusable_workflow_job:
      runs-on: ubuntu-latest
      steps:
      - name: reusable_workflow
        run: |
          echo reusable_workflow_job in Sub Workflow
      
      - name: Echo the input values
        run: |
          echo This is config-path input : ${{ inputs.config-path }}
          echo This is config-value input : ${{ inputs.config-value }}
      
      # - uses: actions/labeler@v4
      #   with:
      #     repo-token: ${{ secrets.envPAT }}
      #     configuration-path: ${{ inputs.config-path }}
