name: Sub Workflow

on:
    workflow_dispatch:
    workflow_call:
      inputs:
        config-path:
          required: false
          type: string
      secrets:
        envPAT:
          required: false

jobs:
    sub-job1:
      runs-on: ubuntu-20.04
      steps:
      - name: sub-job1
        run: echo sub-job1

    reusable_workflow_job:
      runs-on: ubuntu
      steps:
      - name: reusable_workflow
        run: |
          echo reusable_workflow_job
        # with:
        #   repo-token: ${{ secrets.envPAT }}
        #   configuration-path: ${{ inputs.config-path }}

        