name: Reusable Workflow user

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Run a one-line script
        run: echo Hello, world in Reusable Workflow!
      

  # docker:
  #   uses: AksharaDeena/reusable-workflow/.github/workflows/main.yml@main
  #   with:
  #     image_name: my-awesome-app
  #     tag: ${{github.run_number}}
  #   secrets:
  #     registry_username: ${{secrets.REGISTRY_USERNAME}}
  #     registry_password: ${{secrets.REGISTRY_PASSWORD}}
